# CI 项目
name: CleanRelease

# CI 权限
permissions: write-all

# CI 计划
on:
  # 自动运行: 当 CompileZeroWrt 完成后
  workflow_run:
    workflows: ["CompileZeroWrt"]
    types:
      - completed
  # 手动运行
  workflow_dispatch:

# CI 环境
env:
  # GITHUB ENV
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# CI 任务
jobs:
  clean-release:
    name: CleanRelease
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: DeleteReleasesAndWorkflowsRun
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_tags: true
          delete_releases: true
          releases_keep_latest: 4
          releases_keep_keyword: 'IPQ60XX-WiFi_NO-251005'
          delete_workflows: true
          workflows_keep_day: 1
          workflows_keep_keyword: ''
